/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lib */

#ifndef _Included_lib
#define _Included_lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lib
 * Method:    process
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_lib_process
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
